name: Yitan-Survey-App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  android-tests:
    runs-on: windows-latest  # Windows runner

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Set up Android SDK on Windows
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # Step 4: Set ANDROID_HOME and update PATH
      - name: Set ANDROID_HOME and update PATH (Windows)
        shell: cmd
        run: |
          echo ANDROID_HOME=%ANDROID_SDK_ROOT%>> %GITHUB_ENV%
          echo %ANDROID_SDK_ROOT%\platform-tools>> %GITHUB_PATH%

      # Step 5: Install Android system image & platform tools
      - name: Install system image
        shell: cmd
        run: |
          echo y | %ANDROID_SDK_ROOT%\cmdline-tools\latest\bin\sdkmanager.bat "system-images;android-30;google_apis;x86"
          echo y | %ANDROID_SDK_ROOT%\cmdline-tools\latest\bin\sdkmanager.bat "platforms;android-30"
          echo y | %ANDROID_SDK_ROOT%\cmdline-tools\latest\bin\sdkmanager.bat "platform-tools"

      # Step 6: Create Android Emulator
      - name: Create Android Emulator
        shell: cmd
        run: |
          %ANDROID_SDK_ROOT%\cmdline-tools\latest\bin\avdmanager.bat create avd -n testEmulator -k "system-images;android-30;google_apis;x86" -d pixel

      # Step 7: Start Emulator
      - name: Start Emulator
        shell: cmd
        run: |
          %ANDROID_SDK_ROOT%\emulator\emulator.exe -avd testEmulator -no-snapshot -noaudio -no-boot-anim -gpu off -no-window ^
          && timeout /t 60 ^
          && adb wait-for-device ^
          && adb shell input keyevent 82

      # Step 8: Install Node & Appium (server only)
      - name: Set up Node.js (for Appium server)
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Appium server
        run: |
          npm install -g appium@2.11.3
          appium driver install uiautomator2

      # Step 9: Start Appium server
      - name: Start Appium server
        run: |
          appium --base-path /wd/hub --log-level info &
        shell: bash

      # Step 10: Build project with Maven (skip tests first)
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Step 11: Run Appium + Selenium + Cucumber Tests
      - name: Run Tests
        run: mvn test

      # Step 12: Upload Cucumber test reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports/
